import {styled, keyframes} from "@stitches/react";

const Loading = ({fullscreen}) => {
  return (
    <>
      {fullscreen == false ? (
        <>
          <div className="loadingio-spinner-ellipsis-5gjswmnlybw">
            <div className="ldio-isthm47abo">
              <div></div>
              <div></div>
              <div></div>
              <div></div>
              <div></div>
            </div>
          </div>
          <style type="text/css">
            {`@keyframes ldio-isthm47abo {
   0% { transform: translate(12px,80px) scale(0); }
  25% { transform: translate(12px,80px) scale(0); }
  50% { transform: translate(12px,80px) scale(1); }
  75% { transform: translate(80px,80px) scale(1); }
 100% { transform: translate(148px,80px) scale(1); }
}
@keyframes ldio-isthm47abo-r {
   0% { transform: translate(148px,80px) scale(1): }
 100% { transform: translate(148px,80px) scale(0); }
}
@keyframes ldio-isthm47abo-c {
   0% { background: #0055a5 }
  25% { background: #ce64a6 }
  50% { background: #bda0b2 }
  75% { background: #45aee7 }
 100% { background: #0055a5 }
}
.ldio-isthm47abo div {
  position: absolute;
  width: 40px;
  height: 40px;
  border-radius: 50%;
  transform: translate(80px,80px) scale(1);
  background: #0055a5;
  animation: ldio-isthm47abo 1s infinite cubic-bezier(0,0.5,0.5,1);
}
.ldio-isthm47abo div:nth-child(1) {
  background: #45aee7;
  transform: translate(148px,80px) scale(1);
  animation: ldio-isthm47abo-r 0.25s infinite cubic-bezier(0,0.5,0.5,1), ldio-isthm47abo-c 1s infinite step-start;
}.ldio-isthm47abo div:nth-child(2) {
  animation-delay: -0.25s;
  background: #0055a5;
}.ldio-isthm47abo div:nth-child(3) {
  animation-delay: -0.5s;
  background: #45aee7;
}.ldio-isthm47abo div:nth-child(4) {
  animation-delay: -0.75s;
  background: #bda0b2;
}.ldio-isthm47abo div:nth-child(5) {
  animation-delay: -1s;
  background: #ce64a6;
}
.loadingio-spinner-ellipsis-5gjswmnlybw {
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
  background: none;
}
.ldio-isthm47abo {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-isthm47abo div { box-sizing: content-box; }`}
            {/* generated by https://loading.io/ */}
          </style>
        </>
      ) : (
        <StyledLoading>
          <div className="loadingio-spinner-dual-ring-4n4s82tu0rh">
            <div className="ldio-9bkhntgx6ct">
              <div></div>
              <div>
                <div></div>
              </div>
            </div>
          </div>
          <style type="text/css">
            {`@keyframes ldio-9bkhntgx6ct {
  0% { transform: rotate(0) }
  100% { transform: rotate(360deg) }
}
.ldio-9bkhntgx6ct div { box-sizing: border-box!important }
.ldio-9bkhntgx6ct > div {
  position: absolute;
  width: 72px;
  height: 72px;
  top: 14px;
  left: 14px;
  border-radius: 50%;
  border: 8px solid #000;
  border-color: #e2e2e2 transparent #e2e2e2 transparent;
  animation: ldio-9bkhntgx6ct 1s linear infinite;
}
.ldio-9bkhntgx6ct > div:nth-child(2) { border-color: transparent }
.ldio-9bkhntgx6ct > div:nth-child(2) div {
  position: absolute;
  width: 100%;
  height: 100%;
  transform: rotate(45deg);
}
.ldio-9bkhntgx6ct > div:nth-child(2) div:before, .ldio-9bkhntgx6ct > div:nth-child(2) div:after { 
  content: "";
  display: block;
  position: absolute;
  width: 8px;
  height: 8px;
  top: -8px;
  left: 24px;
  background: #e2e2e2;
  border-radius: 50%;
  box-shadow: 0 64px 0 0 #e2e2e2;
}
.ldio-9bkhntgx6ct > div:nth-child(2) div:after { 
  left: -8px;
  top: 24px;
  box-shadow: 64px 0 0 0 #e2e2e2;
}
.loadingio-spinner-dual-ring-4n4s82tu0rh {
  width: 100px;
  height: 100px;
  display: inline-block;
  overflow: hidden;
  background: none;
}
.ldio-9bkhntgx6ct {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-9bkhntgx6ct div { box-sizing: content-box; }`}
            {/* generated by https://loading.io/ */}
          </style>
        </StyledLoading>
      )}
    </>
  );
};

const show = keyframes({
  "0%": {opacity: 0},
  "100%": {opacity: 1},
});

const StyledLoading = styled("div", {
  background: `rgba(0, 0, 0, 0.834)
      url('../public/Ellipsis-1s-200px.svg') center
      no-repeat`,
  position: "fixed",
  display: "flex",
  alignItems: "center",
  justifyContent: "center",
  pointerEvents: "none",
  inset: 0,
  zIndex: 1,
  "@media (prefers-reduced-motion: no-preference)": {
    animation: `${show} 150ms cubic-bezier(0.16, 1, 0.3, 1) forwards`,
  },
});

export default Loading;
