import "../styles/globals.css";
import Head from "next/head";
import "bootstrap/dist/css/bootstrap.css";
import "jquery";
import { styled } from "@stitches/react";
import { slateDark } from "@radix-ui/colors";

function MyApp({ Component, pageProps }) {
  return (
    <Root>
      <Head>
        <title>Todo List</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Component {...pageProps} />
    </Root>
  );
}

const Root = styled("div", {
  backgroundColor: slateDark.slate2,
  display: "flex",
  justifyContent: "center",
});

export default MyApp;
