import "../styles/globals.css";
import Head from "next/head";
import "bootstrap/dist/css/bootstrap.css";
import "jquery";
import { styled } from "@stitches/react";
import { generateHsl } from "../utils";

const hsl = generateHsl()

function MyApp({ Component, pageProps }) {
  return (
    <>
      <style jsx global>
        {`
          body {
            background: ${hsl};
          }
          div#__next {
            display: flex;
            width: 100%;
            height: 100%;
          }`
        }
      </style>
      <Head>
        <title>Tudu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/css2?family=PT+Sans+Narrow&family=Raleway&display=swap" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css2?family=Raleway&display=swap" rel="stylesheet" />
      </Head>
      <Container>
        <Component {...pageProps} />
      </Container>
    </>
  );
}

const Container = styled("div", {
  height: "100%",
  width: "100%",
  display: "flex",
  flexDirection: 'column',
  alignItems: 'center',
  justifyContent: "center",
});

export default MyApp;
